### ISSUE TITLE
Add support for suite-level lifecycle hooks

### ISSUE THREAD

**Issue by alexp1917** [micronaut-projects/micronaut-test#462]
### Feature description

I am trying to run my expensive database/testcontainer/migration work up front and not over again for every new test class. I think the way to accomplish this is to build it into this plugin by adding a/static field(s) into the abstract junit extension class. I hope that junit will eventually support it natively (junit-team/junit5#456) and when that happens, then the static fields can simply be taken out, and the methods that get called can simply be moved into methods for the junit hook per suite hook vs the per container(test class) hook.

**Comment by alexp1917** [comment]
after two hours of coding it up - the difficulty is mostly that introduces a ton of new code. also [posted about it on the micronaut gitter](https://gitter.im/micronautfw/questions?at=614eefc8f3449e13a491660c).

**Comment by alexp1917** [comment]
going to close this issue but hopefully if anyone has the same idea as me they can just find this issue and re-engage here.

**Comment by swaechter** [comment]
Hey maybe not a 100% perfect solution, but I ran into the same issue: I want to start my Testcontainers only once and do cleanup/data loading before each test. I came up with the following solution:

1.) Create a new annotation `ExtendedMicronautTest` that should be used instead of `MicronautTest`. We define a custom extension that is executed before the MicronautJunit5Extension extension (Really important)

```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.ANNOTATION_TYPE, ElementType.TYPE})
@ExtendWith({BaseExtension.class, MicronautJunit5Extension.class})
@MicronautTest(rollback = false, transactional = false)
public @interface ExtendedMicronautTest {
}
```

2.) Create a new JUnit extension that will be executed once before all tests and once after all tests:

```java
public class BaseExtension implements BeforeAllCallback, BeforeEachCallback, ExtensionContext.Store.CloseableResource {

    private static final AtomicBoolean initialized = new AtomicBoolean(false);

    private static PostgreSQLContainer<?> postgresqlContainer;

    @Override
    public void beforeAll(ExtensionContext context) throws Exception {
        if (!initialized.get()) {
            // Create and start the Postgresql Testcontainers instance and get the port
            postgresqlContainer = startDatabaseContainer();
            databasePort = postgresqlContainer.getMappedPort(TestGlobals.DATABASE_PORT);

            // Set the extension as started
            initialized.set(true);

            // Register a close handler to stop the database container
            context.getRoot().getStore(ExtensionContext.Namespace.GLOBAL).put("cleanup_handler", this);
        }
    }

    @Override
    public void beforeEach(ExtensionContext context) throws Exception {
        // Do your database cleanup
        // TODO: Implement
    }

    @Override
    public void close() throws Throwable {
        // Stop the container
        postgresqlContainer.stop();
    }

    private PostgreSQLContainer<?> startDatabaseContainer() {
        // Create the database container
        PostgreSQLContainer<?> localPostgresqlContainer = new PostgreSQLContainer<>("postgres:13")
            .withDatabaseName(TestGlobals.DATABASE_NAME)
            .withUsername(TestGlobals.DATABASE_USERNAME)
            .withPassword(TestGlobals.DATABASE_PASSWORD)
            .withExposedPorts(TestGlobals.DATABASE_PORT);

        // Start it
        localPostgresqlContainer.start();

        // Return it
        return localPostgresqlContainer;
    }
}
```

3.) Write a simple test while using the new annotation `ExtendedMicronautTest`:

```java
@ExtendedMicronautTest
public class AccountServiceTest {

    @Inject
    private AccountService accountService;

    @Test
    public void testLogin() throws Exception {
    }
}
```

**Comment by alvarosanchez** [comment]
@swaechter have you looked at [Micronaut Test Resources](https://micronaut-projects.github.io/micronaut-test-resources/latest/guide/)? It seems to fit your needs.

You have a detailed explanation at @melix 's blog: https://melix.github.io/blog/2022/08/micronaut-test-resources.html

**Comment by swaechter** [comment]
Hi @alvarosanchez yes I saw that feature and really like it. I guess the code I posted doesn't show the real purpose: I want to use `MicronautJunit5Extension`, but before all/each test I **need** to create an initial settings file and set `System.setProperty("micronaut.config.files", <settings path>)` to this settings file so each test can manipulate the settings (Or better: Implement `TestPropertyProvider` in the test base class so we don't polute the properties - we want to run tests in parallel).

Defining an abstract base test class with BeforeAll/BeforeEach annotations + letting each test extend this class doesn't work, because `MicronautJunit5Extension.beforeAll` is executed before the BeforeAll in the base test. When the application context/embedded server (?) is started, the settings file is not yet created.

It's quite hard to describe the problem and I don't know how to ask devs for their advice - any ideas?

**Comment by swaechter** [comment]
Hmm...maybe I can set up the settings file in a custom resource that implements `TestResourcesResolver `. I'll look into that :)

**Comment by alexanderankin** [comment]
@alvarosanchez - just got pinged about this again on slack, seems like a real need regardless of micronaut test resources

**Comment by alvarosanchez** [comment]
If specific to Docker support, it would be better to create an issue in https://github.com/micronaut-projects/micronaut-test-resources.

Otherwise I think https://github.com/junit-team/junit5/issues/456 should come first.
