### ISSUE TITLE
JUnit 5 - @Value / @Property is not supported when injecting in constructor

### ISSUE THREAD

**Issue by FylmTM** [micronaut-projects/micronaut-test#69]
Hi,

With `1.1.0` release it is now possible to define constructor for test class to inject application beans.

However it does not work with `@Value` or `@Property`.

Code:
```
@IntegrationTest
class AuthenticationFilterTest(
    private val testData: TestData,
    private val dslContext: DSLContext,
    @Value("\${portal.sessions.duration}")
    private val sessionsDuration: Duration
) {
// ...
}
```

Error:
```
org.junit.jupiter.api.extension.ParameterResolutionException: No ParameterResolver registered for parameter [java.time.Duration arg2] in constructor [public app.components.authentication.AuthenticationFilterTest(app.testsupport.TestData,org.jooq.DSLContext,java.time.Duration)].
```

Meanwhile our workaround is to use field inject for `@Value`.
Example:

```
@IntegrationTest
class AuthenticationFilterTest(
    private val testData: TestData,
    private val dslContext: DSLContext
) {

    @Value("\${portal.sessions.duration}")
    private lateinit var sessionsDuration: Duration
    // ...
}
```

**Comment by graemerocher** [comment]
I think it will probably work with `@field:Value(..)`

**Comment by FylmTM** [comment]
@graemerocher 

I have tried. Same error.

```
@IntegrationTest
class AuthenticationFilterTest(
    private val testData: TestData,
    private val dslContext: DSLContext,
    @field:Value("\${portal.sessions.duration}")
    private val sessionsDuration: Duration
) {
  // ...
}
```

```
org.junit.jupiter.api.extension.ParameterResolutionException: No ParameterResolver registered for parameter [java.time.Duration arg2] in constructor [public app.portal.components.authentication.AuthenticationFilterTest(app.portal.testsupport.TestData,org.jooq.DSLContext,java.time.Duration)].
```

**Comment by graemerocher** [comment]
Ah yeah, looks like a missing feature in the impl

**Comment by jameskleeh** [comment]
I can't reproduce this

**Comment by distinctdan** [comment]
I just ran into an instance of this that appeared to be an incremental compilation bug, but I can't reproduce it. I had a constructor `@Value` that it was failing to find in my `application-test.yml`, until I made an unrelated change to the `application-test.yml` and rebuilt. I'm not sure what happened, it's possible I might have canceled a tests run at some point, might have affected the build. I've tried a few times to reproduce it, but everything is working now, but thought I should still comment since it was stuck for a while where it couldn't find it.
