### ISSUE TITLE
TestPropertyProvider interface not working in kotlintest

### ISSUE THREAD

**Issue by jisikoff** [micronaut-projects/micronaut-test#82]
Create a kotlin project which includes the io.kotlintest.provided bootstrap stuff:
```
mn create-app testtest --lang=kotlin
```
getProperties() is never called and the values are never injected 
 [on this line context is always null](https://github.com/micronaut-projects/micronaut-test/blob/master/test-kotlintest/src/main/kotlin/io/micronaut/test/extensions/kotlintest/MicronautKotlinTestContext.kt#L17)

```
@MicronautTest
class PropertySourceTest(@Property(name = "rabbitmq.host") val suppliedValue: String) :BehaviorSpec(), TestPropertyProvider{

     init {
        given("a property source") {
            `when`("the value is injected") {
                then("the correct value is injected") {
                    suppliedValue shouldBe "testhost"
                }
            }
        }
    }

    override fun getProperties(): Map<String, String> {
        return mapOf(
                "rabbitmq.host" to "testhost"
        )
    }
}
```

**Comment by jdbranham** [comment]
Any chance this could still be affecting certain use cases?  
https://stackoverflow.com/questions/59744402/how-do-i-use-testpropertyprovider-and-inject-rxhttpclient-with-micronaut-using-k

**Comment by jdbranham** [comment]
I think I misunderstood the original post. 
I understand now there's no fix for this, because the class is instantiated before the properties are provided.
Although I was able to use the workaround for field injection.

https://stackoverflow.com/questions/59744402/how-do-i-use-testpropertyprovider-and-inject-rxhttpclient-with-micronaut-using-k
